name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install linter
        run: pip install flake8

      - name: Run linter
        run: flake8 .